;; This logfile was generated automatically by `xindy'
;; at 02.04.2017  16:47:07
;; Indexstyle: "C:\\Users\\SL-Th\\OneDrive\\Dokumente\\DHBW\\Studienarbeit\\FleeAndCatch-Docs\\documentation\\6jH6EQ_Plw", Rawindex: "C:\\Users\\SL-Th\\OneDrive\\Dokumente\\DHBW\\Studienarbeit\\FleeAndCatch-Docs\\documentation\\wlGi85PY6H", Output: "dokumentation.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "€È¨" -> "A"
Letter-group: "¤Ú»´" -> "H"
Letter-group: "†ÐÐ" -> "C"
Letter-group: "ë»´" -> "X"
Letter-group: "à¨" -> "U"
Letter-group: "€ÃÚ" -> "A"
Letter-group: "€Ë»" -> "A"
Letter-group: "¨´" -> "I"
Letter-group: "¬¨Ú" -> "J"
Letter-group: "´´" -> "D"
Letter-group: "†´¨" -> "C"
Letter-group: "†´Ë" -> "C"
Letter-group: "€ÈÈ" -> "A"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "€ÃÚ" -> "A"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "†´¨" -> "C"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "´´" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¤Ú»´" -> "H"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¨´" -> "I"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¬¨Ú" -> "J"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "à¨" -> "U"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ë»´" -> "X"